// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzkoxpgsdzbmqxbiyuqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6a294cGdzZHpibXF4Yml5dXFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgwOTkzMjEsImV4cCI6MjA5MzY3NTMyMX0.WkyBppjSZCgArFyq7dF4HkQ-Hkksha7zeT0yu2wo8Xk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});